name: Deploy to OVH

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run linting
        run: npm run lint
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: dist/
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/web-cv:latest
            ghcr.io/${{ github.repository_owner }}/web-cv:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Verify image push
        run: |
          echo "Vérification de l'image pushée..."
          docker pull ghcr.io/${{ github.repository_owner }}/web-cv:latest
          docker images | grep ghcr.io/${{ github.repository_owner }}/web-cv
          echo "Image vérifiée avec succès"
      
      - name: Deploy to OVH Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.OVH_HOST }}
          username: ${{ secrets.OVH_USERNAME }}
          key: ${{ secrets.OVH_SSH_KEY }}
          port: ${{ secrets.OVH_PORT }}
          script: |
            cd ~/web-cv
            
            # Mettre à jour le repository
            git pull origin main
            
            # Créer le fichier .env avec les variables nécessaires
            cat > .env << EOF
            GITHUB_REPOSITORY_OWNER=${{ github.repository_owner }}
            GITHUB_USERNAME=${{ github.repository_owner }}
            DOCKER_USERNAME=${{ github.repository_owner }}
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            DOMAIN=${{ secrets.DOMAIN }}
            ACME_EMAIL=${{ secrets.ACME_EMAIL }}
            TRAEFIK_AUTH=${{ secrets.TRAEFIK_AUTH }}
            NODE_ENV=production
            EOF
            
            # Charger et exporter les variables d'environnement
            set -a
            source .env
            set +a
            
            # Exporter explicitement les variables critiques
            export GITHUB_REPOSITORY_OWNER="${{ github.repository_owner }}"
            export GITHUB_USERNAME="${{ github.repository_owner }}"
            export DOCKER_USERNAME="${{ github.repository_owner }}"
            export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
            export DOMAIN="${{ secrets.DOMAIN }}"
            export ACME_EMAIL="${{ secrets.ACME_EMAIL }}"
            export TRAEFIK_AUTH="${{ secrets.TRAEFIK_AUTH }}"
            export NODE_ENV=production
            
            # Vérifier les variables d'environnement
            echo "Variables d'environnement:"
            echo "GITHUB_REPOSITORY_OWNER=${GITHUB_REPOSITORY_OWNER}"
            echo "DOMAIN=${DOMAIN}"
            
            # Configurer le contexte Docker par défaut
            docker context use default
            
            # Authentification Docker avec GitHub Container Registry
            if echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.repository_owner }}" --password-stdin; then
                echo "Authentification Docker réussie"
            else
                echo "Erreur: L'authentification Docker a échoué"
                exit 1
            fi
            
            # Vérifier l'image avant le pull
            echo "Tentative de pull de l'image: ghcr.io/${{ github.repository_owner }}/web-cv:latest"
            
            # Attendre un moment pour la synchronisation
            sleep 5
            
            # Tester l'image manuellement avec retry
            for i in {1..3}; do
                echo "Tentative $i de pull de l'image..."
                if docker pull ghcr.io/${{ github.repository_owner }}/web-cv:latest; then
                    echo "Pull réussi à la tentative $i"
                    break
                elif [ $i -eq 3 ]; then
                    echo "Échec du pull après 3 tentatives"
                    echo "Diagnostic des problèmes potentiels:"
                    echo "- Vérification des images disponibles:"
                    docker images | grep ghcr.io/${{ github.repository_owner }}/web-cv || echo "Aucune image trouvée"
                    echo "- Statut de l'authentification:"
                    docker system info | grep -E "(Registry|Username)" || echo "Pas d'info d'authentification"
                    exit 1
                else
                    echo "Tentative $i échouée, retry dans 10 secondes..."
                    sleep 10
                fi
            done
            
            # Vérifier le contenu du fichier docker-compose.yml
            echo "Contenu du fichier docker-compose.yml (lignes image):"
            grep -n "image:" docker-compose.yml || echo "Aucune ligne image trouvée"
            
            # Vérifier la configuration docker-compose
            echo "Configuration docker-compose avec substitution:"
            docker-compose config | grep -A 1 "image:"
            
            # Vérifier la substitution des variables
            echo "Test de substitution manuelle:"
            echo "Variable GITHUB_REPOSITORY_OWNER: ${GITHUB_REPOSITORY_OWNER}"
            echo "Image attendue: ghcr.io/${GITHUB_REPOSITORY_OWNER}/web-cv:latest"
            
            # Déploiement
            docker-compose pull
            docker-compose down --remove-orphans
            docker-compose up -d
            docker system prune -f
            
            # Nettoyage des credentials
            docker logout ghcr.io